// Code generated by controller-gen. Hand-written equivalent.
// Regenerate by running: controller-gen object:headerFile="hack/boilerplate.go.txt" paths="./api/..."

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

func (in *OIDCRoleBinding) DeepCopyInto(out *OIDCRoleBinding) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *OIDCRoleBinding) DeepCopy() *OIDCRoleBinding {
	if in == nil {
		return nil
	}
	out := new(OIDCRoleBinding)
	in.DeepCopyInto(out)
	return out
}

func (in *OIDCRoleBinding) DeepCopyObject() runtime.Object {
	return in.DeepCopy()
}

func (in *OIDCRoleBindingList) DeepCopyInto(out *OIDCRoleBindingList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OIDCRoleBinding, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *OIDCRoleBindingList) DeepCopy() *OIDCRoleBindingList {
	if in == nil {
		return nil
	}
	out := new(OIDCRoleBindingList)
	in.DeepCopyInto(out)
	return out
}

func (in *OIDCRoleBindingList) DeepCopyObject() runtime.Object {
	return in.DeepCopy()
}

func (in *OIDCRoleBindingSpec) DeepCopyInto(out *OIDCRoleBindingSpec) {
	*out = *in
	if in.ClusterRoleRef != nil {
		in, out := &in.ClusterRoleRef, &out.ClusterRoleRef
		*out = new(ClusterRoleRef)
		**out = **in
	}
	if in.RoleRef != nil {
		in, out := &in.RoleRef, &out.RoleRef
		*out = new(RoleRef)
		**out = **in
	}
}

func (in *OIDCRoleBindingSpec) DeepCopy() *OIDCRoleBindingSpec {
	if in == nil {
		return nil
	}
	out := new(OIDCRoleBindingSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *OIDCRoleBindingStatus) DeepCopyInto(out *OIDCRoleBindingStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *OIDCRoleBindingStatus) DeepCopy() *OIDCRoleBindingStatus {
	if in == nil {
		return nil
	}
	out := new(OIDCRoleBindingStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *ClusterRoleRef) DeepCopy() *ClusterRoleRef {
	if in == nil {
		return nil
	}
	out := new(ClusterRoleRef)
	*out = *in
	return out
}

func (in *RoleRef) DeepCopy() *RoleRef {
	if in == nil {
		return nil
	}
	out := new(RoleRef)
	*out = *in
	return out
}
